---
kind: pipeline
type: docker
name: Update Relic Data

steps:
  - name: generate
    image: node:lts-alpine
    commands:
      - yarn
      - yarn export

  - name: update Git
    image: alpine/git
    user: root
    commands:
      - chmod +x ./update.sh
      - ./update.sh
    environment:
      ACCESS_TOKEN:
        from_secret: ghToken
    when:
      branch:
        - master