---
kind: pipeline
type: docker
name: Update Relic Data

steps:
  - name: generate
    image: node:lts-alpine
    commands:
      - yarn
      - yarn export

  - name: update Git
    image: alpine/git
    commands:
      - WARFRAME_BUILD=`cat ./data/version`
      - git config user.name "Titania CI"
      - git config user.email "titaniaci@sleepylux.xyz"
      - git commit -m "📝 Update(items) for Warframe Version $WARFRAME_BUILD"
      - git remote rm origin
      - git remote add origin https://$ACCESS_TOKEN:x-oauth-basic@github.com/TitaniaProject/warframe-relic-data
      - git push -u origin master
    environment:
      ACCESS_TOKEN:
        from_secret: ghToken
    when:
      branch:
        - master